beam_search fix for running with torch.use_deterministic_algorithms(True)
Context:
Pytorch has some bugs related to setting values for tensors to scalars when using torch.use_deterministic_algorithms that were only addressed in most recent Pytorch versions. See:
* https://github.com/pytorch/pytorch/commit/2d4b1ae434d28ed66b3c96cd47e21d648bd6a0b8
* https://github.com/pytorch/pytorch/issues/68525

The scalar attribution in beam_search.forward would throw:
```
    RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel()INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":250, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor31
```
when running with torch.use_deterministic_algorithms(True).

The change in the CR did not have any changes in performance, but works around the 2 bugs mentioned above.

Testing done:
* Ran with a custom model, using `torch.use_deterministic_algorithms(True)`